apiVersion: v1
kind: Pod
metadata:
  name: simple-app3
  namespace: demo
spec:
  containers:
    - name: app-simple
      image: vietaws/eks:v2
      ports:
        - containerPort: 8080
      resources:
        requests:
          # memory: "0.3Gi"
          cpu: "300m"
        limits:
          # memory: "1Gi"
          cpu: "900m"
