apiVersion: v1
kind: Namespace
metadata:
  name: demo

---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
  namespace: demo
spec:
  limits:
    - default: # this section defines default limits
        cpu: 800m
      defaultRequest: # this section defines default requests
        cpu: 500m
      max: # max and min define the limit range
        cpu: "1" #1000m
      min:
        cpu: 100m
      type: Container
